### ISSUE TITLE
Request for device support H600D

### ISSUE THREAD

**Issue by Just4Link** [boergegrunicke/ioBroker.govee-local#123]
I search for new gu10 lights cause my milights are slowly dying and found the govee gu10 H600D lights. Do this adapter support these GU10 H600D lights?

Here is the link to the govee homepage for the lights:

https://eu.govee.com/products/govee-rgbww-smart-light-bulbs?variant=48308962754744

**Comment by boergegrunicke** [comment]
According to the compatibility guide from Govee, this model does not support the local API.
So this will most likely work only with the cloud-based adapter, as long as Govee does not bring and update to support local control.

**Comment by Just4Link** [comment]
what is the recent cloud based adapter? in the iobroker repository i can nothing find.

**Comment by boergegrunicke** [comment]
Sorry, I am not sure about that, as I am currently not using it myself.
