### ISSUE TITLE
cannot delete adapter

### ISSUE THREAD

**Issue by gidhap** [boergegrunicke/ioBroker.govee-local#54]
unfortunately my devices are not supported by the local api, so I have to uninstal the adapter.
However this doesn't work.
`$ iobroker del govee-local --debug

Delete adapter "govee-local"

Error deleting adapter govee-local from disk: Cannot find module 'iobroker.govee-local/io-package.json'Require stack:- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupInstall.js- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupUpgrade.js- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js- /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js

You might have to delete it yourself!

Process exited with code 0`

ioBroker is up to date.
Node.js v18.16.0
NPM 9.5.1
Admin 6.12.0

**Comment by boergegrunicke** [comment]
I assume, this is not a problem of the adapter, but your specific installation ...

**Comment by gidhap** [comment]
txs for the feedback. 
Any other adapter can be installed or uninstalled, except this one. However, I'll simply leave it deactivated for the time being.
