### ISSUE TITLE
Govee erscheint nicht

### ISSUE THREAD

**Issue by Skol6** [boergegrunicke/ioBroker.govee-local#55]
Hallo,

hab bei meinem Govee LED Strip die Option "LAN Steuerung" aktiviert.
Aber er erscheint nicht im Adapter. Muss ich da noch irgendwas einstellen?

Vielen Dank.

**Comment by Skol6** [comment]
Eventuell kann der Adapter für Homebridge hier weiterhelfen.
Dort sind so gut wie alle LED Strips integriert
[https://github.com/bwp91/homebridge-govee](url)

**Comment by boergegrunicke** [comment]
In was für einer Umgebung läuft es denn? Gibt es im Log irgendetwas?
Da zwangsläufig UDP verwendet werden muss, können Netzwerkbeschränkungen ein Problem sein, auch unter Windows war es etwas umständlich, das überhaupt zum Laufen zu bekommen. Daher wären ein paar mehr Informationen über die Umgebung ganz hilfreich

**Comment by Skol6** [comment]
Hab den LED Strip gegen einen anderen getauscht. jetzt klappt es einwandfrei.
