### ISSUE TITLE
feature request: RGB value instead of 3 separate values

### ISSUE THREAD

**Issue by thogens** [boergegrunicke/ioBroker.govee-local#61]
Hi,

the adapter currently only supports 3 separate values for r, g and b and this is not really working in any other adapter.
Would it be possible to make the adapter at least compatible with "light control"?
That would mean to have one read/write value for the color that translates it into the separate values for the lights.
Thomas

**Comment by boergegrunicke** [comment]
Sorry, I am not familiar with the light control adapter. Does it need a special format, or is it just about reacting on change, when the color code is updated from outside the adapter?

**Comment by thogens** [comment]
HI,
I was referring to light control, as this seems to be the easiest way to get things running together with any other color light bulbs.
I just took a look and it seems light control as well accepts colours in HEX format #FFFFFF. 
So if you would calculate the HEX value out of the 3 separate RGB values (and vice versa) it could work in both ways.
Light control could read and write that value for control the source.

**Comment by boergegrunicke** [comment]
Version 0.2.0 supports reading AND writing the color as HEX color code. It should be available on the latest channel soon. Please let me know if this works, how you need it.

**Comment by boergegrunicke** [comment]
Is there any log output from the adapter?
On what environment is it running?

**Comment by thogens** [comment]
What logs do you need or what info do you need? I logged a starting sequence, but there is a ton of data in it...
I'm using Docker on Synology server.
