### ISSUE TITLE
Feedback: Smart Curtain Lights is found

### ISSUE THREAD

**Issue by JojoS62** [boergegrunicke/ioBroker.govee-local#62]
**Describe the bug**  
No Bug, just a feedback.

I have installed the iOS app and the light curtain was found by BLE. Then activated Wifi and enabled 'LAN Steuerung'.
The adapter could find the device and the objects are shown in ioBroker.

The number of datapoints are only a subset as for your Govee light. Is it possible to control the effects and other settings? Is there a documented API?
Anyway, thanks for this adapter.

**Expected behavior**  
everything is fine

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 5.0.17
 - Node version: v18.18.2
 - Operating system: ubuntu 22.04

**Comment by boergegrunicke** [comment]
Unfortunately, the documentation only shows, how to generally deal with it. As far as I know, there is no public documentation, that lists all available methods/data per device. I just checked the responses from the lamps, and constructed it from this. But unfortunately, I do not own this curtain, so I cannot check this one by myself.

**Comment by boergegrunicke** [comment]
@JojoS62
In Version 0.2.0, that should be available in the latest repository soon, there is an option "extended logging". If the log level is set to `info` and this option is enabled, it will write the data from the device to the ioBroker log. If you could send me the data, that it prints, I could take a look, if this gives a hint about more available features.
