### ISSUE TITLE
H705B - Govee RGBIC Permanent Outdoor Lights

### ISSUE THREAD

**Issue by Ringo-66** [boergegrunicke/ioBroker.govee-local#63]
Feature / include request:

Please include device: "H705B - Govee RGBIC Permanent Outdoor Lights"

after switching on the LAN support of the device, the report shows:

govee-local.0 | 2023-12-15 18:33:09.145 | silly | States  system redis pmessage  system.adapter.govee-local.0.logLevel/system.adapter.govee-local.0.logLevel:{"val":"silly","ack":true,"ts":1702661589143,"q":0,"from":"system.adapter.govee-local.0","lc":1702661447942}
govee-local.0 | 2023-12-15 18:33:09.142 | debug | UDP listening on 0.0.0.0:4002
govee-local.0 | 2023-12-15 18:33:09.132 | info | starting. Version 0.1.2 in PATH.../iobroker.govee-local, node: v18.17.0, js-controller: 4.0.24
govee-local.0 | 2023-12-15 18:33:08.985 | silly | statesDB connected
govee-local.0 | 2023-12-15 18:33:08.984 | debug | States connected to redis: 127.0.0.1:9000
govee-local.0 | 2023-12-15 18:33:08.962 | debug | States create User PubSub Client
govee-local.0 | 2023-12-15 18:33:08.962 | debug | States create System PubSub Client
govee-local.0 | 2023-12-15 18:33:08.949 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
govee-local.0 | 2023-12-15 18:33:08.948 | silly | objectDB connected
govee-local.0 | 2023-12-15 18:33:08.946 | silly | redis psubscribe cfg.o.enum.*
govee-local.0 | 2023-12-15 18:33:08.931 | silly | redis psubscribe cfg.o.system.user.*
govee-local.0 | 2023-12-15 18:33:08.930 | debug | Objects connected to redis: 127.0.0.1:9001
govee-local.0 | 2023-12-15 18:33:08.926 | debug | Objects client initialize lua scripts
govee-local.0 | 2023-12-15 18:33:08.860 | debug | Objects create User PubSub Client
govee-local.0 | 2023-12-15 18:33:08.860 | debug | Objects create System PubSub Client
govee-local.0 | 2023-12-15 18:33:08.859 | debug | Objects client ready ... initialize now
govee-local.0 | 2023-12-15 18:33:08.832 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
govee-local.0 | 2023-12-15 18:33:05.301 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
govee-local.0 | 2023-12-15 18:33:05.300 | info | terminating
govee-local.0 | 2023-12-15 18:33:05.300 | info | Got terminate signal TERMINATE_YOURSELF
govee-local.0 | 2023-12-15 18:33:05.299 | silly | States  system redis pmessage  system.adapter.govee-local.0.sigKill/system.adapter.govee-local.0.sigKill:{"val":-1,"ack":false,"ts":1702661585300,"q":0,"from":"HOST","lc":1702661585300}

The objecttree is nearly empty.. (admin / 0-info-connection (true) ) nothing else.

i can support with logs and tests if needed...

**Comment by boergegrunicke** [comment]
@Ringo-66 
Not quite sure, if this will work, like I expect it. But let's try it: In version 0.2.0, that should be available on the latest channel soon (or right now, installing from GitHub), I included an option "extended logging". If you set the log level for this adapter to info and enable this option, the adapter will write to the log all the data, that it receives from all devices (only one time after adapter start). If you could send this information, probably I have an idea, how to support this device.

**Comment by boergegrunicke** [comment]
> [govee_log.txt](https://github.com/boergegrunicke/ioBroker.govee-local/files/13845502/govee_log.txt)
> 
> hopefully you can find something interesting (and helpfull :) )

Unfortunately, no. There is visible, that the adapter was restarted, but nothing more. After a few seconds, the adapter should find devices and start logging their data.
Does your adapter currently find devices? It looks like your system is running on Windows. Unfortunately, windows does not like to give Node.js access to the UDP multicast packages...

**Comment by boergegrunicke** [comment]
It looks like it is working normally on Windows when selecting the correct network interface (the default, all interfaces, does not work). An option to select the correct interface is integrated in version 0.2.5 (should be in latest today or tomorrow).
Please select the interface that has your local IP address and let me know if it is working. Also, the extended logging option should provide additional information afterward.

**Comment by boergegrunicke** [comment]
Version 0.2.4 is still the previous version 😉 As I released version 0.2.5 after midnight, it might be synced to the latest repository not today, but tomorrow, however nice if it is already working!
