### ISSUE TITLE
Version 0.2.0 ohne onOff -Funktion

### ISSUE THREAD

**Issue by ohle64** [boergegrunicke/ioBroker.govee-local#65]
v0.2.0 komplett unbenutzbar. Beim setzen von onOff auf true im Objekt-Browser(Admin) wird der Wert erst auf true geändert und nach Ablauf der scan-Zeit zurück gesetzt auf false. Die LED-Strips bleiben aus. Umgekehrt das gleiche. Wenn ich über die App(Handy) den Strip einschalte, kann der ioBroker ihn nicht ausschalten.
Keine Meldungen im Log ausser send scan (nach eingestelltem Interval z.Z. 60s)
Habe 2x LED-Strip H619A und 1x H6159
Die Version 0.1.2 läuft ohne Problem.

**Comment by wm20320** [comment]
Here problems with OnOff, too - but different. Switch OnOff --> true works, Switch OnOff --> false doesn't.
No such issue with 0.1.2
(H619A - H6172)

**Comment by boergegrunicke** [comment]
Thanks, there was a logical mistake. This will be fixed with the next release!
