### ISSUE TITLE
Namen werden nicht angezeigt

### ISSUE THREAD

**Issue by reihd** [boergegrunicke/ioBroker.govee-local#73]
Hallo,

es werden leider keine Namen angezeigt, also wenn man sehr viele Geräte hat, ist es unmöglich da den Überblick zu behalten. Vielleicht gibt es ja eine Lösung dafür.  Ich mache mir im Moment immer eine neue Variable in dem Ordner mit dem Namen der Lampe.

**Comment by boergegrunicke** [comment]
Die Informationen, die da von den Geräten kommen, sind leider sehr spärlich. Die einzigen gerätespezifischen Informationen, sind IP und Mac-Adresse.

**Comment by reihd** [comment]
ja ok, dass habe ich mir schon gedacht, leider ist das so.
