### ISSUE TITLE
keine Verbindung zwischen ioBroker und Govee H7065

### ISSUE THREAD

**Issue by Alfons012024** [boergegrunicke/ioBroker.govee-local#75]
Hi,

ich hoffe Du kannst mir ein bischen mehr Klarheit in die Kommunikation von den Govee Geräten geben. Ich habe das Problem, dass sich scheinbar der ioBroker und der H7065 nicht sehen.
Wie sollte die Kommunikation für gewöhnlich laufen?
Was habe ich bereits gemacht?
Ich habe mir die Govee Home App auf mein Smartphone installiert und per Bluetooth mich mit dem Govee Gerät verbunden. Im weiteren habe ich die WLAN Einstellungen angepasst und den Schalter der "Lan Steuerung aktiviert". Mit der App funktioniert alles super, auch wenn man Bluetooth abschaltet und nur über WLAN kommuniziert. Aber ist kein Internet vorhanden, dann ist nichts mehr möglich (aber das interessiert ja nicht mit Deinem Adapter). Mein Smartphone und das Govee Gerät sind im gleichen WLAN (und IP-Netz).
Im ioBroker habe ich den Adapter installiert.
Ich benutze für die Kommunikation zwei unterschiedliche IP Netze Ein Hausautomations-LAN und ein Hausautomations-WLAN), die keinen Internetzugang haben. Der ioBroker auf meinem Raspi4, 2 GB (alles soweit von der softwareseite aktualisiert) ist per Ethernet (LAN Kabel verbunden)
Ich habe erfahren, dass Govee ausschließlich UDP für die Kommunikation benutzt. Ist das richtig? Ich habe daraufhin mal ein Powershell Script auf meinem Windows PC geschrieben, welcher im gleichen WLAN Netz, wie das Govee Gerät ist und habe mal eine UDP-Message an den ioBroker (im anderen IP Netz) geschickt. Dieses konnte ich im Debug Log des ioBroker zu sehen. Somit funktioniert scheinbar die UDP Verbindung.
Jetzt komme ich allerdings nicht weiter. Hast Du da noch eine Idee woran es liegen könnte, dass das Govee Gerät nicht im iobroker sichtbar wird? Muss irgendetwas noch im Gerät konfiguriert oder initiert werden, damit Govee irgendwas an ioBroker sendet?
Vielen Dank schon mal vorab für Diene Hilfe.

Gruß

**Comment by boergegrunicke** [comment]
Soweit richtig, die lokale Kommunikation geschieht über UDP. Außerdem muss der Adapter sich in einer Multicast-Gruppe eintragen. Die Gerätesuche erfolgt über die Multicast-Adresse, alles danach direkt per IP → IP. Wenn du noch einen weiteren Rechner hast, der theoretisch damit kommunizieren kann, könntest du mal versuchen, mit diesem `239.255.255.250` beizutreten und zu schauen, ob die Scan-Nachricht auf Port 4001 ankommt (standardmäßig alle 10 Sekunden). Wenn nicht, gibt es vielleicht ein Problem mit der Weiterleitung der Multicast-Nachrichten. Zwischen mehreren Netzen könnte das generell schwierig werden, weil ein stumpfes Routing nicht ausreicht, wegen der Multicast Geschichten.
