### ISSUE TITLE
Brightness will overrides Kelvin setting with same value

### ISSUE THREAD

**Issue by realwax** [boergegrunicke/ioBroker.govee-local#81]
After setting the level the Kelvin is set to the same value which is a bug. It changes Kelvin where it's not meant  to  be.
only happen ins 0.25 the latest.

Thank you

**Comment by boergegrunicke** [comment]
It is fixed in version 0.2.6. Feel free, to check it from latest repository.

**Comment by realwax** [comment]
Thank you! Yes, I can confirm it is fixed.
