### ISSUE TITLE
govee2mqtt

### ISSUE THREAD

**Issue by krobipd** [boergegrunicke/ioBroker.govee-local#99]
Hallo

und erstmal vielen Dank für deinen Adapter. Bevor ich mich für Govee Leds entschieden hatte hab ich viel recherchiert und musst staunen das es fürn iobroker nicht viel gibt obwohl die Leds ja sehr beliebt sind, günstig und weit verbreitet.

hab dann den https://github.com/TA2k/ioBroker.govee-app Adapter gefunden und mich gewundert, wird schon länger nicht mehr gewartet und scheint jetzt recht tot zu sein. dann hab ich deinen adapter gefunden und mich erst sehr gefreut aber musste recht schnell feststellen das die lokale api seitens govee doch sehr beschränkt ist.

nach meiner weiteren Recherche hab ich das hier gefunden https://github.com/wez/govee2mqtt
find ich sehr genial und wollte dich mal auf dieses Projekt aufmerksam machen vl kann man das ja weiter nutzen für den Ausbau von diesen adapter.

statt das auf mqtt umzumodeln usw könnte man das ganze dann ja direkt in den broker einbauen. ich bin selbst nicht mehr Entwicklung tätig, daher ist es jetzt einfach mal großes reden. aber vl kanntest du dieses Projekt noch nicht und weckt dein Interesse.

**Comment by boergegrunicke** [comment]
@krobipd
Das Projekt kenne ich durchaus, damit steuere ich aktuell meine Govee-Geräte! 😉
Da das nicht für Node.JS entwickelt wurde, lässt sich davon nichts wirklich übernehmen, es könnte lediglich als Inspiration für eine Implementation in JavaScript oder TypeScript dienen. Das Ganze ist ja schon ziemlich gewachsen und so etwas zu implementieren ist keine Sache von ein paar Stunden. Da ich selbst inzwischen produktiv nicht mehr den ioBroker nutze, steht es leider in keinem Verhältnis mehr für mich eine derart aufwendige Lösung zu bauen.

Wenn ich das richtig sehe, sollte das doch aber auch völlig losgelöst als Docker-Container laufen, den könntest du auf deinem ioBroker Host laufen lassen, an den mqtt-Adapter anbinden und so auch mit dem ioBroker davon profitieren.
